// Builds public/data/bathrooms.json from NYC Open Data, plus data/hours-review.md
// listing Brooklyn restrooms whose hours need a human check.
//
// Run: npm run data

import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { parseHours } from '../src/lib/hours.js';

const DATASET = 'https://data.cityofnewyork.us/resource/i7jb-7jku.json?$limit=5000';
const METADATA = 'https://data.cityofnewyork.us/api/views/i7jb-7jku.json';
const OVERRIDES = new URL('../data/hours-overrides.json', import.meta.url);
const OUT = new URL('../public/data/bathrooms.json', import.meta.url);
const REVIEW = new URL('../data/hours-review.md', import.meta.url);

// Socrata's "Borough Boundaries" computed region codes (verified against known parks).
const BOROUGHS = { 1: 'Staten Island', 2: 'Brooklyn', 3: 'Queens', 4: 'Manhattan', 5: 'Bronx' };

const clean = (s) => (s ?? '').replace(/^"|"$/g, '').trim() || null;

// The dataset has no ID column, so derive a stable one from name + coordinates.
const idFor = (r) => 'nyc-' + createHash('sha1').update(`${r.facility_name}|${r.latitude}|${r.longitude}`).digest('hex').slice(0, 10);

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  return res.json();
}

const [rows, meta, overrides] = await Promise.all([
  fetchJson(DATASET),
  fetchJson(METADATA),
  readFile(OVERRIDES, 'utf8').then(JSON.parse),
]);

const review = [];
const bathrooms = [];
for (const r of rows) {
  const lat = Number(r.latitude);
  const lng = Number(r.longitude);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;

  const id = idFor(r);
  const borough = BOROUGHS[r[':@computed_region_yeji_bk3q']] ?? null;
  let { hours, flags } = parseHours(r.hours_of_operation);
  const override = overrides[id];
  if (override) {
    hours = override.hours;
    flags = [];
  }
  if (borough === 'Brooklyn' && flags.length) {
    review.push({ id, name: r.facility_name, flags, raw: r.hours_of_operation ?? '' });
  }

  bathrooms.push({
    id,
    name: r.facility_name,
    type: r.location_type ?? null,
    operator: r.operator ?? null,
    borough,
    status: r.status ?? null,
    season: r.open ?? null,
    hoursText: clean(r.hours_of_operation),
    hours,
    hoursReviewed: Boolean(override),
    accessibility: clean(r.accessibility),
    restroomType: clean(r.restroom_type)?.replace('Single -Stall', 'Single-Stall') ?? null,
    changingStations: clean(r.changing_stations),
    notes: clean(r.additional_notes),
    website: r.website?.url ?? null,
    lat,
    lng,
  });
}

const sourceUpdatedAt = new Date(meta.rowsUpdatedAt * 1000).toISOString();
await mkdir(new URL('.', OUT), { recursive: true });
await writeFile(
  OUT,
  JSON.stringify({ generatedAt: new Date().toISOString(), sourceUpdatedAt, count: bathrooms.length, bathrooms }) + '\n',
);

const byFlag = Map.groupBy(review, (r) => r.flags[0].replace(/-\w+day$/, ''));
const reviewMd = [
  '# Brooklyn hours to review',
  '',
  `Generated by \`npm run data\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand — fix entries in`,
  '`data/hours-overrides.json` (keyed by id) and rerun. Until fixed, these show "Hours unknown" (or are read as daily, for `assumed-daily`).',
  '',
  ...[...byFlag].flatMap(([flag, items]) => [
    `## ${flag} (${items.length})`,
    '',
    '| id | name | flags | source text |',
    '|---|---|---|---|',
    ...items.map((i) => `| ${i.id} | ${i.name} | ${i.flags.join(', ')} | ${i.raw.replace(/\s*\n\s*/g, ' / ').replace(/\|/g, '\\|')} |`),
    '',
  ]),
].join('\n');
await writeFile(REVIEW, reviewMd);

const brooklyn = bathrooms.filter((b) => b.borough === 'Brooklyn');
const count = (list, fn) => list.filter(fn).length;
console.log(`Wrote ${bathrooms.length} restrooms (${brooklyn.length} in Brooklyn). City data last updated ${sourceUpdatedAt.slice(0, 10)}.`);
console.log(`Brooklyn: ${count(brooklyn, (b) => b.status === 'Operational')} operational, ${count(brooklyn, (b) => b.hours)} with structured hours, ${review.length} flagged for review → data/hours-review.md`);
